version: '2.4'
services:
  master:
    image: pubsub
    ports: 
    - "7476:7476"
    volumes:
    - type: bind
      source: ./config/master_slave
      target: /config
    environment:
    - CONFIG=/config/master.textpb
    cpus: 0.50
    mem_limit: 2G
  
  slave-0:
    depends_on: 
    - master
    build: 
      context: ../
    image: pubsub
    ports: 
    - "7477:7476"
    volumes:
    - type: bind
      source: ./config/master_slave
      target: /config
    environment:
    - CONFIG=/config/slave-0.textpb
    cpus: 0.50
    mem_limit: 2G

  slave-1:
    depends_on:
    - master
    image: pubsub
    ports: 
    - "7478:7476"
    volumes:
    - type: bind
      source: ./config/master_slave
      target: /config
    environment:
    - CONFIG=/config/slave-1.textpb
    cpus: 0.50
    mem_limit: 2G
  
  slave-2:
    depends_on:
    - slave-0
    image: pubsub
    ports: 
    - "7479:7476"
    volumes:
    - type: bind
      source: ./config/master_slave
      target: /config
    environment:
    - CONFIG=/config/slave-2.textpb
    cpus: 0.50
    mem_limit: 2G
