version: '2.4'
services:
  pubsub:
    image: pubsub
    ports: 
    - "7476:7476"
    volumes:
    - type: bind
      source: ./config/single_machine
      target: /config
    environment:
    - CONFIG=/config/server.textpb
    cpus: 0.50
    mem_limit: 2G
