name: benchmark
on: [push]
jobs:
  single-machine-benchmark:
    strategy:
      matrix:
        number-of-client: [500x, 1000x, 2000x]
    runs-on: ubuntu-latest
    steps:
    - name: checkout-code
      uses: actions/checkout@v2
    - name: build-docker-image
      run: make docker
    - name: single-machine-benchmark
      run: |
        make single-machine-up
        sleep 5
        go test -bench=BenchmarkSingleMachine -count=3 -benchtime=${{ matrix.number-of-client }} -v ./simulation/...
    
  master-slave-benchmark:
    strategy:
      matrix:
        number-of-client: [1500x, 3000x, 5000x]
    runs-on: ubuntu-latest
    steps:
    - name: checkout-code
      uses: actions/checkout@v2
    - name: build-docker-image
      run: make docker
    - name: master-slave-benchmark
      run: |
        make master-slave-up
        sleep 5
        go test -bench=BenchmarkMasterSlave -count=3 -benchtime=${{ matrix.number-of-client }} -v ./simulation/...
