name: benchmark
on: [push]
jobs:
  single-machine-benchmark:
    strategy:
      matrix:
        number-of-client: [200x]
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: checkout-code
      uses: actions/checkout@v2
    - name: build-docker-image
      run: make docker
    - name: single-machine-benchmark
      run: |
        make single-machine-up
        go test -bench=BenchmarkSingleMachine -benchtime=${{ matrix.number-of-client }} -v ./simulation/...
    
  master-slave-benchmark:
    strategy:
      matrix:
        number-of-client: [500x]
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: checkout-code
      uses: actions/checkout@v2
    - name: build-docker-image
      run: make docker
    - name: master-slave-benchmark
      run: |
        make master-slave-up
        go test -bench=BenchmarkMasterSlave -benchtime=${{ matrix.number-of-client }} -v ./simulation/...
