name: benchmark
on: [push]
jobs:
  single-machine-benchmark:
    strategy:
      matrix:
        number-of-client: [200]
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: golang-env-setup
      uses: actions/setup-go@v1
      with:
        go-version: 1.14.x
    - name: install-proto-compiler
      uses: arduino/setup-protoc@master
    - name: checkout-code
      uses: actions/checkout@v2
    - name: install-dependencies
      run: make dependencies
    - name: build-docker-image
      run: make docker
    - name: build-simulation-binary
      run: make simulation
    - name: single-machine-benchmark
      run: |
        make single-machine-up
        bin/simulation --upper=${{ matrix.number-of-client }} :7476
    
  master-slave-benchmark:
    strategy:
      matrix:
        number-of-client: [500]
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: golang-env-setup
      uses: actions/setup-go@v1
      with:
        go-version: 1.14.x
    - name: install-proto-compiler
      uses: arduino/setup-protoc@master
    - name: checkout-code
      uses: actions/checkout@v2
    - name: install-dependencies
      run: make dependencies
    - name: build-docker-image
      run: make docker
    - name: build-simulation-binary
      run: make simulation
    - name: master-slave-benchmark
      run: |
        make master-slave-up
        bin/simulation --upper=${{ matrix.number-of-client }} :7476 :7477 :7478 :7479

  raft-benchmark:
    strategy:
      matrix:
        number-of-client: [500]
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: golang-env-setup
      uses: actions/setup-go@v1
      with:
        go-version: 1.14.x
    - name: install-proto-compiler
      uses: arduino/setup-protoc@master
    - name: checkout-code
      uses: actions/checkout@v2
    - name: install-dependencies
      run: make dependencies
    - name: build-docker-image
      run: make docker
    - name: build-simulation-binary
      run: make simulation
    - name: raft-benchmark
      run: |
        make raft-up
        bin/simulation --upper=${{ matrix.number-of-client }} :7476 :7477 :7478 :7479
