on: [push, pull_request]
name: ci
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.12.x, 1.13.x, 1.14.x]
    runs-on: ubuntu-latest
    steps:
    - name: golang-env-setup
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    - name: install-proto-compiler
      uses: arduino/setup-protoc@master
    - name: checkout-code
      uses: actions/checkout@v2
    - name: install-dependencies
      run: |
        go get -u ./...
        go get -u github.com/golang/protobuf/protoc-gen-go
        go get -u google.golang.org/grpc
    - name: test
      run: make test
